apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2020-03-23T13:58:15Z"
  generation: 10
  labels:
    app: kubernetes-demo-app
  name: kubernetes-demo-app
  namespace: default
  resourceVersion: "1239944"
  selfLink: /apis/apps/v1/namespaces/default/deployments/kubernetes-demo-app
  uid: 5779c5bf-6d0e-11ea-af8f-42010aa6017d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubernetes-demo-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubernetes-demo-app
    spec:
      containers:
        - image: gcr.io/ivory-haven-271511/kubernetes-demo-app@sha256:d07590025552a657a2e2729db9ca88fb138160083de4fe0cdfb9fceb87075875
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          name: kubernetes-demo-app-sha256-1
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 5
  conditions:
    - lastTransitionTime: "2020-03-23T13:58:15Z"
      lastUpdateTime: "2020-03-23T14:25:27Z"
      message: ReplicaSet "kubernetes-demo-app-55b464b77c" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2020-03-23T14:31:07Z"
      lastUpdateTime: "2020-03-23T14:31:07Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 10
  readyReplicas: 5
  replicas: 5
  updatedReplicas: 5
